name: Apply Checker

on:
  # 5분마다 자동 실행
  schedule:
    - cron: '*/5 * * * *'
  
  # 수동 실행 (GitHub UI 또는 n8n에서 트리거)
  workflow_dispatch:
    inputs:
      mode:
        description: '실행 모드'
        required: false
        default: 'once'
        type: choice
        options:
          - once
          - adjust

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run Apply Checker
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          ALIGO_API_KEY: ${{ secrets.ALIGO_API_KEY }}
          ALIGO_USER_ID: ${{ secrets.ALIGO_USER_ID }}
          ALIGO_SENDER: ${{ secrets.ALIGO_SENDER }}
          PAYSSAM_API_KEY: ${{ secrets.PAYSSAM_API_KEY }}
          PAYSSAM_MEMBER: ${{ secrets.PAYSSAM_MEMBER }}
          PAYSSAM_MERCHANT: ${{ secrets.PAYSSAM_MERCHANT }}
        run: |
          MODE="${{ github.event.inputs.mode || 'once' }}"
          python apply_checker.py $MODE
